import { Inter as FontSans } from "next/font/google";
import type { Metadata } from "next";
import { Providers } from "@/components/providers";
import AppBar from "@/components/app-bar";
import { cn } from "@/lib/utils";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col h-[100vh] min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
